#To host local: mkdocs serve
#To publish: 
#cd ../hello-robot.github.io/
#mkdocs gh-deploy --config-file ../stretch_docs/mkdocs.yml --remote-branch master
#Sizing images: convert foo.png -resize x100 foo_rs.png
#Local site: 127.0.0.1:8000
site_name: Stretch User Docs
repo_url: https://github.com/hello-robot/stretch_docs
site_description: "Hello Robot User Documentation"
use_directory_urls: True
nav:
 - Home: README.md
 - Quick Start: quick_start_guide.md
 - Software:
    - Stretch Body Package: stretch_body_guide.md
    - Stretch ROS Package: stretch_ros_guide.md
 - Hardware:
    - Robot Safety: robot_safety_guide.md
    - Robot Care: robot_care_guide.md
    - User Guide: hardware_user_guide.md
 - Forum: "https://forum.hello-robot.com/"
theme:
 name: sandstone
 logo: images/hello_robot_logo.png
extra_css: [extra.css]

